# Generated by Django 3.0.3 on 2022-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201004_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='url_name',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='nswf',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='translating_status',
        ),
        migrations.AddField(
            model_name='manga',
            name='content_type',
            field=models.ManyToManyField(to='core.ContentType'),
        ),
        migrations.AddField(
            model_name='manga',
            name='translating_status',
            field=models.ManyToManyField(to='core.TranslatingStatus'),
        ),
    ]
