# Generated by Django 3.0.3 on 2022-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220904_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
