# Generated by Django 3.0.3 on 2022-09-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220904_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='title',
            new_name='ru_title',
        ),
        migrations.AddField(
            model_name='manga',
            name='eng_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='manga',
            name='jp_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
