# Generated by Django 3.0.3 on 2022-09-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220904_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_moto',
        ),
    ]
