# Generated by Django 3.0.3 on 2022-09-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220904_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Comic', 'verbose_name_plural': 'Comics'},
        ),
        migrations.AddField(
            model_name='manga',
            name='loaded_by_parser',
            field=models.BooleanField(default=False),
        ),
    ]
