# Generated by Django 3.0.3 on 2022-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('core', '0035_auto_20220904_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='periodic_task',
            field=models.ManyToManyField(to='django_celery_beat.PeriodicTask'),
        ),
    ]
