# Generated by Django 3.0.3 on 2022-09-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('core', '0037_auto_20220904_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='periodic_task',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
