# Generated by Django 3.0.3 on 2022-09-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220904_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='periodic_task',
        ),
    ]
