# Generated by Django 3.0.3 on 2022-09-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('core', '0039_remove_manga_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='periodic_task',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
            preserve_default=False,
        ),
    ]
